service: kamalduo-app
image: scarver2/kamalduo-app
servers:
  web:
    - demo.a1webconsulting.com
registry:
  server: localhost:5555
proxy:
  ssl: true
  hosts:
    - kamalduo.a1webconsulting.com
  app_port: 9292
  healthcheck:
    path: /healthz
    interval: 3
    timeout: 5
builder:
  arch: amd64
